name: Check .NET

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-tests:
    uses: ./.github/workflows/build.yml
    secrets: 
      token: ${{ secrets.NUGET_TOKEN }}
